server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
            uri : https://github.com/rahuljadhav3626/Myrepo/tree/main
             clone-on-start:true